services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DB_NAME=$DB_NAME
        - DB_USER=$DB_USER
        - DB_USER_PASSWORD=$DB_USER_PASSWORD
        - DB_ROOT_PASSWORD=$DB_ROOT_PASSWORD
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
volumes:
  mariadb: